### PR TITLE
Adding Fire Watch Skelly

### PR DESCRIPTION
**Pull request by Akiyama64**
See previous pull attempt here https://github.com/Civcraft/EnvironmentalEffects/pull/16

Also, the identifier line refuses to work with the YAML. If there is a way to make that line of code work, then it'd be nice, but this is the only valid YAML I could make so far. (Notice the identifier is commented out.)

### CODE REVIEW

**Comment by Maxopoly** [comment]
What do you mean they dont work with the yaml? Also you can remove most of the options there, because they are having the same value as the default one (see the explainations below the example config you copied from). 

Are you aware that the spawn chance of this thing is about as high as that of all other mobs combined? Not really opposed, but just wanted to note that.

Also is it intended that the player gets speed 1 if he's shot by that mob?

**Comment by Akiyama64** [comment]
This is what happens if I use the identifier: http://prntscr.com/at7cyi According to http://www.yamllint.com/

Yes, it is a high spawn rate. Still, it's limited to the birch forest biome and grass to spawn on. The birch forests of Aleph have been emptied of birch, and they still don't grow birch if you plant new saplings. That kind of spawn would make the birch forest biomes (which are small in number) gain some attention.

As for the speed 1 if you get hit by this mob, that's intended. Keep in mind that the clock in the skelly's hand is knockback five, so the speed debuff shouldn't be useful to swing around him for a counter attack, it is more of a running away hint. Still, if it is too easy on the player, we could eliminate that buff. Also, if it's too easy on players to gather bones from this mob, add some tougher armor on him or reduce the mob spawning rate of it. Could be an interesting expiriment.

**Comment by Maxopoly** [comment]
I'm fine with it, but the identifier is needed. The issue with it is, that your intendation is wrong, it has to be the same one as all the other options (so just add a space).

**Comment by Akiyama64** [comment]
Also, I just realized that your other mobs use a 15 second update time. This new skelly uses a 1 minute refresh time, so it is still rather slow in spawning.

All right, I'll try again with the indenting. Something is pretty weird.

**Comment by Akiyama64** [comment]
All right, it should be fixed now. I was confused earlier about where the identifier should be indented at.

**Comment by Maxopoly** [comment]
Alright, I'll put this up tomorrow.

**Comment by Akiyama64** [comment]
Awesome. Thanks. I'll try things out with a lava bucket on this thing in the morning then. Could be a tough kill along with the other thing in Gimmel.

**Pull request merged**
